# Generated by Django 5.1.4 on 2025-02-01 08:40
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="en-US-u-ks-level2",
            deterministic=False,
        ),
    ]
